#!/bin/sh

# xset dpms force off
# [[!(-n "pidof i3lock")]] && i3exit lock
B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#81A1C1E6'  # default
T='#81A1C1E6'  # text
W='#fb4934E6'  # wrong
V='#689d6aE6'  # verifying

/usr/bin/i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$W       \
--bshl-color=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--time-str="%I:%M %p"  \
--date-str="%A, %m %Y" \
--keylayout 1         \

# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc

