#!/bin/sh
VOLUME=$(pamixer --default-source --get-volume)
if [ "$(pamixer --default-source --get-mute)" = true ]; then
  # notify-send -t 1000 -i ~/Pictures/micmuted.png "Volume" "$VOLUME%"
  dunstify -a "changeMicVolume" -u low -i "$HOME/Pictures/micmuted.png" -t 1000 -h string:x-dunst-stack-tag:"$msgTag" -h int:value:"$VOLUME" "Volume: ${VOLUME}%"
else
  # notify-send -t 1000 -i ~/Pictures/micicon.png "Volume" "$VOLUME%"
  dunstify -a "changeMicVolume" -u low -i "$HOME/Pictures/micicon.png" -t 1000 -h string:x-dunst-stack-tag:"$msgTag" -h int:value:"$VOLUME" "Volume: ${VOLUME}%"
fi
