#!/bin/sh
VOLUME=$(pamixer --default-source --get-volume)
if [ $(pamixer --default-source --get-mute) = true ]; then
  notify-send -t 1000 -i ~/Pictures/micmuted.png "Volume" "$VOLUME%"
else
  notify-send -t 1000 -i ~/Pictures/micicon.png "Volume" "$VOLUME%"
fi
