#!/bin/sh
case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	# Change icon to change wifi down symbol
  down) wifiicon="睊  " ;;
	                               # change icon to change wifi up symbol
#	up) wifiicon="$(awk '/^\s*w/ { print "直", int($3 * 100 / 70) "% " }' /proc/net/wireless)" ;;
  up) wifiicon="$(awk '/^\s*w/ {print "直  "}' /proc/net/wireless)" ;;
esac

                                 # eth down smyb # eth up symb                                             # vpn active symbol
printf "%s%s%s%s\n" "$wifiicon" "$(sed "s/down//;s/up//" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/  /" /sys/class/net/tun*/operstate 2>/dev/null)" "$(sed "s/.*/  /" /sys/class/net/wg*/operstate 2>/dev/null)"

