#!/bin/sh
VOLUME=$(pamixer --get-volume)
if [ "$(pamixer --get-mute)" = true ]; then
  # notify-send -t 1000 -i ~/Pictures/speakermuted.png "Volume" "$VOLUME%"
  dunstify -a "changeVolume" -u low -i "$HOME/Pictures/speakermuted.png" -t 1000 -h string:x-dunst-stack-tag:"$msgTag" -h int:value:"$VOLUME" "Volume: ${VOLUME}%"
else
  # notify-send -t 1000 -i ~/Pictures/speakericon.png "Volume" "$VOLUME%"
  dunstify -a "changeVolume" -u low -i "$HOME/Pictures/speakericon.png" -t 1000 -h string:x-dunst-stack-tag:"$msgTag" -h int:value:"$VOLUME" "Volume: ${VOLUME}%"
fi
