export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export CARGO_HOME=$XDG_DATA_HOME/cargo
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITARM=${DEVKITPRO}/devkitPPC
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export _JAVA_AWT_WM_NONREPARENTING=1
export GOPATH=${HOME}/.local/share/go
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/gtkrc
export LESSHISTFILE=$XDG_CACHE_HOME/less/history
export LUNARVIM_CONFIG_HOME="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
export LUNARVIM_CONFIG_DIR="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-$HOME/.cache/lvim}"
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
# export OBS_USE_EGL=1
export PATH=${DEVKITPRO}/tools/bin:$PATH
export PATH="${PATH}:${HOME}/.local/bin"
export PATH="${PATH}:${HOME}/.config/scripts/statusbar"
export PATH="${PATH}:${GOPATH}/bin"
export QT_QPA_PLATFORMTHEME=qt5ct
# export GDK_SCALE=1.25
# export GDK_DPI_SCALE=0.8
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# export TERMCMD=st
# export TERM=st-256color
export TERMCMD=footclient
export TERM=foot
export XCURSOR_SIZE=24
export XCURSOR_THEME=oreo_nord_snow_3_cursors
# export GTK_THEME=Colloid-Grey-Dark
export CLUTTER_BACKEND="wayland"
export GDK_BACKEND="wayland,x11"
# export SDL_VIDEODRIVER=wayland
export QT_QPA_PLATFORM="wayland;xcb"

export ZDOTDIR=$HOME/.config/zsh
export WINEPREFIX=$XDG_DATA_HOME/wine
