export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITARM=${DEVKITPRO}/devkitPPC
export _JAVA_AWT_WM_NONREPARENTING=1
export GOPATH=/home/albi/.local/share/go
export PATH=${DEVKITPRO}/tools/bin:$PATH
export PATH="${PATH}:/home/albi/.local/bin"
export PATH="${PATH}:/home/albi/.config/scripts/statusbar"
export PATH="${PATH}:${GOPATH}/bin"
export QT_QPA_PLATFORMTHEME=qt5ct
# export GDK_SCALE=1.25
# export GDK_DPI_SCALE=0.8
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
export TERMCMD=st
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export ZDOTDIR=$HOME/.config/zsh
export LUNARVIM_CONFIG_HOME="${LUNARVIM_CONFIG_DIR:-$HOME/.config/lvim}"
export LUNARVIM_RUNTIME_DIR="${LUNARVIM_RUNTIME_DIR:-$HOME/.local/share/lunarvim}"
export LUNARVIM_CACHE_DIR="${LUNARVIM_CACHE_DIR:-$HOME/.cache/lvim}"
