#!/bin/sh
SOURCE=alsa_input.usb-C-Media_Electronics_Inc._USB_PnP_Audio_Device-00.mono-fallback
VOL=$(pacmd list-sources | grep -A6 "$SOURCE" | grep "volume: \(front\|mono\)\|muted:" | grep -o "[0-9]*%" | grep -o "[0-9]*")
case $(pacmd list-sources | grep -A11 "$SOURCE" | awk '/muted/ {print $2; exit}') in
    yes)
      echo " $VOL%"
      ;;
    no)
      echo " $VOL%"
#VOL=$(pacmd list-sources | grep -A6 "$SOURCE" | grep "volume: \(front\|mono\)\|muted:" | grep -o "[0-9]*%")
      ;;
esac
