#!/bin/sh
if [ "$(pidof redshift)" ]
then
  # echo " off"
  PID=$(pidof redshift)
  kill "$PID" > /dev/null
  sleep 5
  pkill -RTMIN+10 dwmblocks > /dev/null 2> /dev/null
else
  # echo " on"
  redshift > /dev/null 2> /dev/null &
  sleep 3
  pkill -RTMIN+10 dwmblocks > /dev/null 2> /dev/null
fi
