#!/bin/sh
# case $BUTTON in
#   1) micmute ;;
#   4) micvolincrease ;;
#   5) micvoldecrease ;;
# esac
# VOL=$(micvolume)
case $BUTTON in
  1) pamixer --default-source -t && pkill -RTMIN+3 dwmblocks;;
  2) switchinput_pipewire && pkill -RTMIN+3 dwmblocks;;
  4) pamixer --default-source -i 5 && pkill -RTMIN+3 dwmblocks;;
  5) pamixer --default-source -d 5 && pkill -RTMIN+3 dwmblocks;;
esac
VOL=$(pamixer --default-source --get-volume)
if [ $(pamixer --default-source --get-mute) = true ]; then
  echo " $VOL%"
else
  echo " $VOL%"
fi
