#!/bin/bash

# Your main_microphone name (or keyword)
# and another device you want switch to (or keyword)
#
# You can find these names (or keywords) by running this command:
#    wpctl status | grep -A3 -m 1 Sources | tail -n 3 |
#
#	EXAMPLE:
#	micName="Blue Snowball"
# 	anotherDevice="HD Pro Webcam"

micName="USB PnP Audio Device Mono"
anotherDevice="NoiseTorch Microphone"


# Getting main_microphone sink id
main_microphone=`wpctl status | grep -A3 -m 1 Sources | tail -n 3 | grep "$micName" | grep -oP '^[^0-9]*\K[0-9]+'`

# Getting another device sink id
device=`wpctl status | grep -A3 -m 1 Sources | tail -n 3 | grep "$anotherDevice" | grep -oP '^[^0-9]*\K[0-9]+'`



if [[ "$(wpctl status | grep -A3 -m 1 Sources | tail -n 3 | grep "\*")" = *"$micName"* ]]; then	
	let nonActive=$device
	nonActiveName=$anotherDevice
	nonActiveIcon=~/Pictures/micicon.png
else
	let nonActive=$main_microphone
	nonActiveName=$micName
	nonActiveIcon=~/Pictures/micicon.png
fi

# Changing output  	
wpctl set-default $nonActive &&

# Sending notification (comment the line below if you don`t want notifications)
notify-send -t 1000 "Audio input" "Switched to $nonActiveName" -u low --icon=$nonActiveIcon
